"""approved not nullable no server default

Revision ID: aa52b103be62
Revises: 5e341aa419a1
Create Date: 2026-05-19 18:29:11.002322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa52b103be62'
down_revision = '5e341aa419a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
